from __future__ import annotations

from typing import Protocol


class DomainActions(Protocol):
    """
    Interface implemented by every domain-specific action handler.

    Pico profiles depend on this interface when dispatching button
    press and release events.
    """

    def press_on(self) -> None: ...

    def release_on(self) -> None: ...

    def press_off(self) -> None: ...

    def release_off(self) -> None: ...

    def press_stop(self) -> None: ...

    def release_stop(self) -> None: ...

    def press_raise(self) -> None: ...

    def release_raise(self) -> None: ...

    def press_lower(self) -> None: ...

    def release_lower(self) -> None: ...
